export const siteConfig = {
  name: "VEXARIA TECHNOLOGIES",
  shortName: "VEXARIA",
  logoSymbol: "VEX",
  logoImage: "/images/alv.webp",
  tagline: "Digital Products. Built Better.",
  heroBadge: "🚀 Digital Product Development Studio",
  description:
    "We build high-performance websites, web applications, and mobile apps that help businesses grow. From idea to launch, we engineer modern digital experiences for startups and enterprises.",
  email: "aadhamshah@gmail.com",
  phone: "+91 63812 48055",
  location: "Tamil Nadu, South India (Global Reach)",
  address: "Coimbatore & Chennai, Tamil Nadu, India",
  responseNotice: "⚡ Typical response time: under 4 hours",

  navLinks: [
    { label: "Home", href: "#hero" },
    { label: "Services", href: "#services" },
    { label: "Solutions", href: "#solutions" },
    { label: "Showcase", href: "#showcase" },
    { label: "Why Us", href: "#why-us" },
    { label: "Process", href: "#process" },
    { label: "Tech Stack", href: "#tech-stack" },
    { label: "Our Work", href: "#portfolio" },
    { label: "Case Study", href: "#case-study" },
    { label: "FAQ", href: "#faq" },
    { label: "Contact", href: "#contact" },
  ],

  services: [
    {
      id: "01",
      title: "Website Development",
      description: "High-performance, fast-loading websites designed to convert visitors into loyal customers.",
      icon: "Globe",
      features: ["Ultra-Fast Speed & Performance", "Modern Web Standards", "Responsive Breakpoints", "Conversion UX Layouts"],
      badge: "Core Service",
    },
    {
      id: "02",
      title: "Web Applications",
      description: "Scalable web applications built around your workflows, complex logic, users, and business goals.",
      icon: "LayoutDashboard",
      features: ["Modern App Architecture", "State & Data Management", "Role-based Dashboards", "API Integration"],
      badge: "High Demand",
    },
    {
      id: "03",
      title: "Mobile Applications",
      description: "Modern cross-platform mobile experiences for iOS and Android with intuitive interfaces and snappy performance.",
      icon: "Smartphone",
      features: ["iOS & Android Apps", "Native-like Performance", "Offline Capability", "Push Notifications"],
      badge: "Popular",
    },
    {
      id: "04",
      title: "Custom Software",
      description: "Business-specific software engineered specifically around your internal operational processes and scale.",
      icon: "Code2",
      features: ["Custom Business Tools", "Legacy Refactoring", "High-Throughput Code", "Scalable Systems"],
      badge: "Enterprise",
    },
    {
      id: "05",
      title: "Cloud & Deployment",
      description: "Reliable production deployment, hosting architecture, automated CI/CD pipelines, and cloud setup.",
      icon: "Cloud",
      features: ["AWS & Cloud Infrastructure", "CI/CD Pipeline Setup", "CDN & Cache Strategies", "99.9% Uptime Design"],
      badge: "Infrastructure",
    },
  ],

  solutions: [
    { title: "Business Website", desc: "Modern corporate digital web presence designed for high credibility and lead conversion.", icon: "Building2" },
    { title: "Customer Portal", desc: "Secure client portals for account management, invoicing, and real-time support.", icon: "Users" },
    { title: "Admin Dashboard", desc: "Data-dense management dashboards with real-time analytics, filtering, and reporting.", icon: "BarChart3" },
    { title: "Booking Platform", desc: "Automated booking, scheduling, and reservation systems built for seamless service flow.", icon: "CalendarCheck" },
    { title: "E-Commerce Platform", desc: "Custom storefronts and checkout workflows tailored for maximum speed and conversion.", icon: "ShoppingBag" },
    { title: "Education Platform", desc: "Interactive learning portals, course management, student progress, and video hubs.", icon: "GraduationCap" },
    { title: "Membership Platform", desc: "Gated content platforms with user tier management and community tools.", icon: "ShieldCheck" },
    { title: "Business Automation", desc: "Automate repetitive data tasks, email notifications, and third-party webhooks.", icon: "Zap" },
  ],

  whyUs: [
    {
      number: "01",
      title: "Business-First Thinking",
      desc: "We don't just write code. We study your target market, monetization strategy, and user journeys to build software that directly impacts revenue.",
    },
    {
      number: "02",
      title: "Modern Technology Stack",
      desc: "Powered by Next.js, TypeScript, and Tailwind CSS. We build on battle-tested frameworks that guarantee longevity, security, and lightning-fast load times.",
    },
    {
      number: "03",
      title: "Performance-Focused",
      desc: "Sub-second load times and 90+ Lighthouse benchmark scores. We treat speed as a foundational feature, optimizing images, scripts, and layout shifts.",
    },
    {
      number: "04",
      title: "Long-Term Scalability",
      desc: "Modular component architecture and clean TypeScript interfaces. Your codebase remains maintainable, well-structured, and ready for future developer handoffs.",
    },
  ],

  processSteps: [
    { number: "01", title: "Discover", desc: "Deep dive into your business goals, target audience, technical requirements, and project scope." },
    { number: "02", title: "Strategy", desc: "Define application architecture, tech stack selection, user flows, and sprint milestones." },
    { number: "03", title: "Design", desc: "Craft intuitive, pixel-perfect UI designs, interactive wireframes, and modern visual design systems." },
    { number: "04", title: "Develop", desc: "Write clean, modular, typed code using Next.js and Tailwind with continuous progress demos." },
    { number: "05", title: "Test", desc: "Rigorous cross-device testing, responsive layout audits, speed optimization, and accessibility checks." },
    { number: "06", title: "Launch", desc: "Production cloud deployment, domain configuration, SEO verification, and live site launch." },
    { number: "07", title: "Grow", desc: "Ongoing maintenance, analytics monitoring, performance updates, and continuous feature expansion." },
  ],

  techStack: [
    { name: "Next.js", category: "Frontend", icon: "Boxes", color: "text-white" },
    { name: "React", category: "Frontend", icon: "Atom", color: "text-cyan-400" },
    { name: "TypeScript", category: "Frontend", icon: "FileCode", color: "text-blue-400" },
    { name: "Tailwind CSS", category: "Frontend", icon: "Palette", color: "text-cyan-300" },
    { name: "Node.js", category: "Backend", icon: "Server", color: "text-emerald-400" },
    { name: "PostgreSQL", category: "Database", icon: "Database", color: "text-blue-300" },
    { name: "Prisma ORM", category: "Database", icon: "Cpu", color: "text-indigo-400" },
    { name: "AWS / Cloud", category: "Cloud", icon: "Cloud", color: "text-slate-200" },
  ],

  portfolioProjects: [
    {
      title: "EduPulse Learning Portal",
      category: "Education Platform",
      description: "Interactive online learning dashboard with course progress tracking, live video streams, and quiz modules.",
      tags: ["Next.js", "TypeScript", "Tailwind CSS", "UI/UX"],
      metrics: "3.2x Student Engagement",
      featured: true,
      accentColor: "from-blue-600 to-cyan-500",
    },
    {
      title: "NovaStore E-Commerce",
      category: "E-Commerce Platform",
      description: "Ultra-fast headless online storefront with dynamic inventory filters, instant search, and sleek checkout experience.",
      tags: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
      metrics: "+42% Conversion Rate",
      featured: true,
      accentColor: "from-cyan-500 to-emerald-500",
    },
    {
      title: "Vanguard Tech Suite",
      category: "Business Website",
      description: "Corporate digital website for an enterprise software firm with interactive product previews and contact funnel.",
      tags: ["TypeScript", "Tailwind CSS", "SEO", "Responsive"],
      metrics: "99/100 Core Web Vitals",
      featured: false,
      accentColor: "from-violet-600 to-blue-600",
    },
    {
      title: "Apex Workshop Hub",
      category: "Workshop Platform",
      description: "Event ticketing and workshop reservation system featuring automated calendar synching and QR ticket generation.",
      tags: ["Next.js", "UI/UX", "Tailwind CSS", "React"],
      metrics: "15k+ Monthly Tickets",
      featured: false,
      accentColor: "from-indigo-600 to-cyan-400",
    },
    {
      title: "ClubMember SaaS",
      category: "Membership Platform",
      description: "Exclusive community portal with subscription tiers, gated knowledge base, and member directory analytics.",
      tags: ["React", "TypeScript", "Tailwind CSS", "Cloud"],
      metrics: "99.9% Uptime Guaranteed",
      featured: false,
      accentColor: "from-blue-500 to-violet-500",
    },

  ],

  caseStudy: {
    title: "From Business Idea to Digital Platform",
    subtitle: "Featured Product Transformation",
    clientIndustry: "B2B Enterprise & Automation",
    challenge: "The client needed a modern, highly scalable B2B portal to digitize manual client onboarding, eliminate spreadsheet tracking, and deliver real-time operational visibility.",
    solution: "VEXARIA TECHNOLOGIES engineered a custom web application paired with a responsive mobile interface. We created intuitive user workflows, automated notifications, and clean analytics.",
    techStack: [],
    results: [
      { label: "Development Speed", value: "Rapid Delivery" },
      { label: "User Onboarding Time", value: "70% Faster" },
      { label: "Lighthouse Speed", value: "98 Score" },
      { label: "Mobile Usability", value: "100% Responsive" },
    ],
  },

  testimonials: [
    {
      quote: "Working with ALVORA TECHNOLOGIES helped us turn our core business idea into a professional digital product in record time. Their attention to detail and UI execution blew our team away.",
      name: "S. Rajesh Kumar",
      role: "Founder & CEO",
      company: "Apex Digital Solutions",
      avatarBg: "bg-blue-600",
      rating: 5,
    },
    {
      quote: "The speed and responsiveness of our new website are remarkable. Page loads are instantaneous and our client inquiries doubled within the first month of launch.",
      name: "Ananya Sundaram",
      role: "Product Lead",
      company: "CloudScale Technologies",
      avatarBg: "bg-cyan-600",
      rating: 5,
    },
    {
      quote: "ALVORA TECHNOLOGIES brings global silicon-valley design standards with deep technical execution. Their clear process made building our web app completely stress-free.",
      name: "K. Vikramaditya",
      role: "Managing Director",
      company: "Vanguard Tech Labs",
      avatarBg: "bg-violet-600",
      rating: 5,
    },
  ],

  faqs: [
    {
      q: "How long does website development take?",
      a: "Typical custom marketing websites take between 2 to 4 weeks depending on page count and custom features. Rapid MVP projects can be delivered in 3 to 4 weeks, while complex enterprise web applications are built in structured multi-week sprint milestones.",
    },
    {
      q: "Can you build custom web applications?",
      a: "Yes! Web application development is one of our primary specializations. We build complex, role-based web applications, customer portals, admin dashboards, and custom software systems using Next.js, React, and TypeScript.",
    },
    {
      q: "Do you develop mobile applications?",
      a: "Absolutely. We design and build modern cross-platform mobile applications for both Android and iOS platforms, delivering native-like performance, smooth animations, and clean UI interfaces.",
    },
    {
      q: "Can you redesign an existing website or legacy system?",
      a: "Yes. We frequently help companies upgrade outdated, slow, or hard-to-maintain legacy websites into modern, high-speed Next.js platforms with enhanced UI/UX, responsive layouts, and SEO improvements.",
    },
    {
      q: "Do you provide maintenance and ongoing support?",
      a: "Yes, we offer ongoing maintenance, security patches, performance monitoring, continuous feature updates, and technical support after your website or application goes live.",
    },
    {
      q: "Can you integrate third-party APIs and services?",
      a: "Yes. We build clean API integrations for payment gateways, CRMs, email tools, authentication systems, cloud storage, analytics, and custom internal microservices.",
    },
  ],

  trustBadges: [
    { name: "Next.js", icon: "Boxes" },
    { name: "React", icon: "Atom" },
    { name: "TypeScript", icon: "FileCode" },
    { name: "Tailwind CSS", icon: "Palette" },
    { name: "Node.js", icon: "Server" },
    { name: "PostgreSQL", icon: "Database" },
    { name: "AWS / Cloud", icon: "Cloud" },
  ],
};
